prefix="github.com/antongulenko/http-isolation-proxy/services"
go install "$prefix/service_bank/bankApi"
go install "$prefix/service_bank"
go install "$prefix/service_catalog/catalogApi"
go install "$prefix/service_catalog"
go install "$prefix/service_payment/paymentApi"
go install "$prefix/service_payment"
go install "$prefix/service_shop/shopApi"
go install "$prefix/service_shop"
go install "$prefix/service_user"
